prevent changes if album or title are actually not changed. using "&&" for control over execution not needed because we're using "set -e"

diff --git a/change_album b/change_album
--- a/change_album
+++ b/change_album
@@ -46,11 +46,18 @@ path_relative_to_album_from_file() {
 apply_change_album() {
     local -r file=$1
     local -r old_album_path=$(albumpath_from_file "$file")
+
+    if [[ $(basename "$old_album_path") = $ALBUM ]]; then
+        echo "[WARN] Cannot change album of $file to \"$ALBUM\", same as old album" >&2
+        return
+    fi
+
     local -r relative_to_album_path=$(path_relative_to_album_from_file "$file")
     local -r newfullpath="$(dirname "$old_album_path")/$ALBUM/$relative_to_album_path"
 
+    # this is a real error case unlike the other check above (which stems from careless user input)
     if [[ -e $newfullpath ]]; then
-        echo "Cannot change album of $file, exists already in $ALBUM: $newfullpath" >&2
+        echo "[ERROR] Cannot change album of $file, file exists already in \"$ALBUM\": $newfullpath" >&2
         exit 1
     fi
 
@@ -58,7 +65,9 @@ apply_change_album() {
         mkdir --parents $(dirname "$newfullpath")
     fi
     
-    mv "$file" "$newfullpath" && echo "$newfullpath"
+    mv "$file" "$newfullpath"
+    
+    echo "$newfullpath"
 }
 
 
diff --git a/set_title b/set_title
--- a/set_title
+++ b/set_title
@@ -46,7 +46,7 @@ apply_set_title() {
     local -r filename=${file##*/}
 
     if [[ $(old_title "$file") = $TITLE ]]; then
-        echo "[WARN] Skipping $file, old title is the same as new title $TITLE" >&2
+        echo "[WARN] Cannot change title of $file to \"$TITLE\", same as old title" >&2
         return
     fi
 
@@ -57,11 +57,11 @@ apply_set_title() {
 
     local -r newfile="$(dirname "$file")/$(new_filename "$filename" "$TITLE")"
 
+    # this is a real error case unlike the other check above (which stems from careless user input)
     if [[ -e $newfile ]]; then
-        echo "[WARN] Cannot change title of $file, file with new title exists: $newfile" >&2
-        return
+        echo "[ERROR] Cannot change title of $file to \"$TITLE\", file $newfile exists already" >&2
+        exit 1
     fi
-
 
     if [[ $file = *.pp[23] ]] || [[ $file = */converted/*.jpg ]]; then
         
@@ -77,8 +77,7 @@ apply_set_title() {
     fi
 
     mv -u "$file" "$newfile"
-
-    # FIXME only execute when mv above worked, put code below into group and && with mv call
+    
     if [[ -v restore_write_protection ]]; then
         chmod u-w "$newfile"
     fi
