change_photo_title can process both a file of photos and photo file parameters

diff --git a/change_photo_title b/change_photo_title
--- a/change_photo_title
+++ b/change_photo_title
@@ -12,29 +12,6 @@ source "$BASEDIR/rawtherapee/lib/sidecar.sh"
 
 PATH="$BASEDIR/metadata:$BASEDIR:$BASEDIR/lib:$PATH"
 
-while getopts "kr" opt; do
-    case $opt in
-        k ) 
-            ADD_TITLE_KEYWORD=;;
-        r )
-            REMOVE_OLD_TITLE_KEYWORD=;;
-	esac
-done
-shift $(expr $OPTIND - 1 )
-
-declare -r NEW_TITLE=${1:-}
-if [[ -z $NEW_TITLE ]]; then
-    echo "[ERROR] Title parameter missing" >&2
-    exit 1
-elif [[ -f $NEW_TITLE || -d $NEW_TITLE ]]; then
-	echo "[ERROR] Title parameter is a file or directory" >&2
-	exit 1
-fi
-
-
-
-PHOTOS_FILE=$2
-
 
 function lookupTitle() {
     local photofile=$1
@@ -67,9 +44,47 @@ function lookupTitle() {
     photoid_get_title "$photoid"
 }
 
-safe_new_title=$(tr ' ' '-' <<<"$NEW_TITLE")
 
-while read -r photo; do
+while getopts "krf:" opt; do
+    case $opt in
+        k ) 
+            ADD_TITLE_KEYWORD=;;
+        r )
+            REMOVE_OLD_TITLE_KEYWORD=;;
+        f )
+            mapfile -t PHOTO_FILES < "$OPTARG"
+            PHOTOS_FILE=$OPTARG;;
+        * ) 
+            echo "Usage: $0 [-k] [-r] -f <photos_file> <new_title>"
+            exit 1;;    
+	esac
+done
+shift $(expr $OPTIND - 1 )
+
+
+declare -r NEW_TITLE=${1:-}
+if [[ -z $NEW_TITLE ]]; then
+    echo "[ERROR] Title parameter missing" >&2
+    exit 1
+elif [[ -f $NEW_TITLE || -d $NEW_TITLE ]]; then
+	echo "[ERROR] Title parameter is a file or directory" >&2
+	exit 1
+fi
+shift 1
+
+
+if ! [[ -v PHOTOS_FILE ]] && [[ $# -gt 0 ]]; then
+    PHOTO_FILES=("$@")
+    PHOTOS_FILE=$(mktemp)
+    tr " " "\n" <<<$* > "$PHOTOS_FILE"
+elif ! [[ -v PHOTOS_FILE ]]; then
+    echo "[ERROR] Photos file parameter missing" >&2
+    exit 1
+fi
+
+
+safe_new_title=$(tr ' ' '-' <<<"$NEW_TITLE")
+for photo in "${PHOTO_FILES[@]}"; do
 
     echo "[INFO] Processing $photo" >&2
 
@@ -118,4 +133,4 @@ while read -r photo; do
 
     done
 
-done < "$PHOTOS_FILE"
+done
