Rewriting change_photo_album, work in progress

diff --git a/change_photo_album b/change_photo_album
--- a/change_photo_album
+++ b/change_photo_album
@@ -1,7 +1,7 @@
 #! /usr/bin/env bash
 
 set -eu
-shopt -s nocasematch
+set -o pipefail
 
 declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")"
 source "$BASE_DIR/lib/directories.sh"
@@ -9,9 +9,26 @@ source "$BASE_DIR/lib/photoid.sh"
 
 PATH="$BASE_DIR/metadata:$BASE_DIR:$PATH"
 
-while getopts "ctao" opt; do
+
+function lookupOldAlbumName() {
+    local photofile=$1
+    
+    # get album name from path (album directory)
+    old_album_path=$(directories_get_albumpath_from_file "$file")
+    old_album=${old_album_path##*/}
+
+    if [[ $old_album =~ - ]]; then
+        echo "${old_album//-/ }"
+
+        
+    else
+        echo "$old_album"
+    fi
+}
+
+
+while getopts "tao" opt; do
     case $opt in
-        c ) shopt -u nocasematch;;
         t ) CHANGE_PHOTO_TITLES_TO_ALBUM_NAME=;;
         a ) ADD_NEW_ALBUM_KEYWORD=;;
         o ) REMOVE_OLD_ALBUM_KEYWORD=;;
@@ -19,49 +36,89 @@ while getopts "ctao" opt; do
 done
 shift $(expr $OPTIND - 1 )
 
-declare -r ALBUM=$(echo "${1:-}" | tr ' ' '-')
-if [[ -z $ALBUM ]]; then
-    echo "[ERROR] Album parameter missing" >&2
-    exit 1
-elif [[ -f $ALBUM || -d $ALBUM ]]; then
+declare -r ALBUM=$1
+if [[ -f $ALBUM || -d $ALBUM ]]; then
 	echo "[ERROR] Album parameter is a file or directory" >&2
 	exit 1
 fi
-shift 1
 
-set -o pipefail
-collect_associated_files "$@" | while read -r file; do 
+PHOTOS_FILE=$2
+
+
+while read -r photo; do
+
+    collect_associated_files "$photo" | while read -r file_in_old_album; do 
+
+        echo "[INFO] Processing $photo: $file_in_old_album" >&2
+
+        if [[ -v REMOVE_OLD_ALBUM_KEYWORD ]]; then
+            old_album_name=$(lookupOldAlbumName "$file_in_old_album")
+            update_keywords "-$old_album_name" "$file_in_old_album"
+        fi
+
+        if [[ -v ADD_NEW_ALBUM_KEYWORD ]]; then
+            update_keywords "$ALBUM" "$file_in_old_album"
+        fi    
+
+        if [[ -v CHANGE_PHOTO_TITLES_TO_ALBUM_NAME ]]; then
+            
+        fi
+
+        # echo "$file_in_new_album"
+
+    done
+
+done < "$PHOTOS_FILE"
+
+# album_dirname=$(tr ' ' '-' <<<"$ALBUM")
+
+
+# 
+# collect_associated_files "$@" | while read -r file; do 
     
-    old_album_path=$(directories_get_albumpath_from_file "$file")
-    old_album=${old_album_path##*/}
+#     old_album_path=$(directories_get_albumpath_from_file "$file")
+#     old_album=${old_album_path##*/}
 
-    if [[ $old_album = $ALBUM ]]; then
-        echo "[WARN] Cannot change album of $file to \"$ALBUM\", same as old album" >&2
-        continue
-    fi
+#     if [[ $old_album = $ALBUM ]]; then
+#         echo "[WARN] Cannot change album of $file to \"$ALBUM\", same as old album" >&2
+#         continue
+#     fi
 
-    relative_to_album_path=${file#$old_album_path/}
-    new_album_parent=${old_album_path%/*}
-    newfullpath="$new_album_parent/$ALBUM/$relative_to_album_path"
+#     relative_to_album_path=${file#$old_album_path/}
+#     new_album_parent=${old_album_path%/*}
+#     newfullpath="$new_album_parent/$ALBUM/$relative_to_album_path"
 
-    if ! [[ -e $(dirname "$newfullpath") ]]; then
-        mkdir --parents "$(dirname "$newfullpath")"
-    elif [[ -e $newfullpath ]]; then
-        echo "[ERROR] Cannot change album of $file, file exists already in \"$ALBUM\": $newfullpath" >&2
-        continue
-    fi
+#     if ! [[ -e $(dirname "$newfullpath") ]]; then
+#         mkdir --parents "$(dirname "$newfullpath")"
+#     elif [[ -e $newfullpath ]]; then
+#         echo "[ERROR] Cannot change album of $file, file exists already in \"$ALBUM\": $newfullpath" >&2
+#         continue
+#     fi
     
-    mv "$file" "$newfullpath"
-    test -v REMOVE_OLD_ALBUM_KEYWORD && update_keywords "-$old_album" "$newfullpath"
-    test -v ADD_NEW_ALBUM_KEYWORD && update_keywords "$ALBUM" "$newfullpath"
-    if [[ -v CHANGE_PHOTO_TITLES_TO_ALBUM_NAME ]]; then
-        old_photoid=$(photoid_get_from_file "$newfullpath")
-        new_photoid=$(photoid_set_title "$old_photoid" "$ALBUM")
-        set_photoid "$newfullpath" "$new_photoid"
-        renamed_file="$(dirname "$newfullpath")/$new_photoid.${newfullpath#*.}"
-        # TODO we could do this a bit more cleverly, without an additional move
-        mv "$newfullpath" "$renamed_file"
-    fi
+#     mv "$file" "$newfullpath"
     
-    echo "$newfullpath"
-done
+#     if [[ -v REMOVE_OLD_ALBUM_KEYWORD ]]; then
+#         # old_album has blanks masked with "-", remove these to get the keyword value
+#         # N.B. of course this will fail if we have an album that originally had "-" in it...
+#         # FIXME introduce remove_keyword_regex
+#         # TBD does jq allow regexes?
+#         old_album_keyword=${old_album//-/ }
+#         update_keywords "-$old_album_keyword" "$newfullpath"
+#     fi
+
+#     if [[ -v ADD_NEW_ALBUM_KEYWORD ]]; then
+#         test -v ADD_NEW_ALBUM_KEYWORD && update_keywords "$ALBUM" "$newfullpath"
+#     fi    
+
+#     if [[ -v CHANGE_PHOTO_TITLES_TO_ALBUM_NAME ]]; then
+#         old_photoid=$(photoid_get_from_file "$newfullpath")
+#         new_photoid=$(photoid_set_title "$old_photoid" "$ALBUM")
+#         # set_photoid "$newfullpath" "$new_photoid"
+#         set_metadata-title "$newfullpath" "$ALBUM"
+#         set-metadata-photoid "$newfullpath" "$new_photoid"
+#         renamed_file="$(dirname "$newfullpath")/$new_photoid.${newfullpath#*.}"
+#         mv "$newfullpath" "$renamed_file"
+#     fi
+    
+#     echo "$newfullpath"
+# done
