import can now been restricted to only raws or jpegs

diff --git a/import_photos b/import_photos
--- a/import_photos
+++ b/import_photos
@@ -18,15 +18,23 @@ cleanup() {
 }
 trap cleanup EXIT
 
-# FIXME add options for
-#   - import raws
-#   - import jpegs
-while getopts "t:a:" opt; do
+declare -r FILETYPES_RAW_ONLY="raw"
+declare -r FILETYPES_JPG_ONLY="jpeg"
+declare -r FILETYPES_RAW_AND_JPG="raw+jpeg"
+
+while getopts "t:a:y:" opt; do
     case $opt in
         a )
             declare -r ALBUM="$(tr ' ' '-' <<<"$OPTARG")";;
         t )
             declare -r TITLE="$(tr ' ' '-' <<<"$OPTARG")";;
+        y )
+            if ! [[ $OPTARG =~ ^${FILETYPES_RAW_ONLY}|${FILETYPES_JPG_ONLY}|${FILETYPES_RAW_AND_JPG}$ ]]; then 
+                echo "[ERROR] Invalid filetypes option $OPTARG"
+                exit 1
+            else 
+                declare -r FILETYPES=$OPTARG
+            fi;;
 	esac
 done
 shift $(expr $OPTIND - 1 )
@@ -34,6 +42,10 @@ shift $(expr $OPTIND - 1 )
 if ! [[ -v ALBUM ]]; then
     echo "[ERROR] No album name given" >&2
     exit $NO_ALBUM_RC
+fi
+
+if ! [[ -v FILETYPES ]]; then
+    declare -r FILETYPES=$FILETYPES_RAW_AND_JPG
 fi
 
 declare -r DCIM_DIR=$(readlink -e "$1")
@@ -127,7 +139,15 @@ if ! [[ -v TITLE ]]; then
     declare -r TITLE=$ALBUM
 fi
 
-declare -r EXTENSIONS=".+\.(ORF|CRW|CR2|RAW|JPG)"
+case $FILETYPES in 
+    $FILETYPES_RAW_ONLY )
+        declare -r EXTENSIONS=".+\.(ORF|CRW|CR2|RAW)";;
+    $FILETYPES_JPG_ONLY )
+        declare -r EXTENSIONS=".+\.(JPG)";;
+    $FILETYPES_RAW_AND_JPG|* )
+        declare -r EXTENSIONS=".+\.(ORF|CRW|CR2|RAW|JPG)";;
+esac
+
 # TODO to use DATE_TAKEN, add another step to pipeline: get date from photofile and compare with DATE, print photofile to stdout
 # if dates match.
 # Using find checks will not work, they only check if newer as a given date
