added gui option

diff --git a/import_photos b/import_photos
--- a/import_photos
+++ b/import_photos
@@ -13,17 +13,19 @@ cleanup() {
 trap cleanup EXIT
 
 
-while getopts "c:k:t:v" opt; do
+while getopts "c:k:t:vg" opt; do
     case $opt in
         c ) 
 			declare -r CREATOR=$OPTARG;;   
 		k ) 
 			# CSV string, using ";". no quoting needed for keywords with blanks
-			declare -r KEYWORDS=$OPTARG;;		
+			declare -r KEYWORDS_OPTION=$OPTARG;;		
         t )
             declare -r SIDECAR_TEMPLATES_DIR=$(readlink -e "$OPTARG");;
 		v )
 			declare -r VERBOSE=;;
+        g )
+            declare -r USE_GUI=;;    
 	esac
 done
 shift $(expr $OPTIND - 1 )
@@ -32,7 +34,6 @@ if ! [[ -v SIDECAR_TEMPLATES_DIR ]]; then
     echo "No sidecar templates dir given or does not exist" >&2
     exit 1
 fi
-
 declare -r DCIM_DIR=$(readlink -e "$1")
 if [[ -z $DCIM_DIR ]]; then
     echo "[ERROR] No DCIM directory given or does not exist" >&2
@@ -43,15 +44,49 @@ if [[ -z $TARGET_DIR ]]; then
     echo "[ERROR] No target directory given or does not exist" >&2
     exit 1
 fi
-declare -r ALBUM=$3
-if [[ -z $ALBUM ]]; then
-    echo "[ERROR] No album name given" >&2
-    exit 1
+
+request_options_from_gui() {
+
+    # TODO add date selector
+  
+    yad \
+		--title="Import photos from DCIM directory $DCIM_DIR" \
+		--form \
+		--field="Album:TEXT" "New photos" \
+        --field="Photo title:TEXT" "New" \
+		--field="Keywords (separated by \";\"):TEXT" "${KEYWORDS_OPTION+$KEYWORD_OPTIONS}" \
+        --field="Only from date:DT" 2> /dev/null
+    
+    if [[ $? = 252 ]]; then
+        echo "[INFO] Cancelled" >&2
+        exit
+    fi
+}
+
+# to set remaining input vars, we either use the gui (if requested) or take them from the command line
+if [[ -v USE_GUI ]]; then
+
+    options_string="$(request_options_from_gui)"
+    echo $options_string >&2
+    declare -r ALBUM="$(echo "$options_string" | cut -d'|' -f 1)"
+    declare -r TITLE="$(echo "$options_string" | cut -d'|' -f 2)"
+    keywords_string="$(echo "$options_string" | cut -d'|' -f 3)"
+    test -n "$keywords_string" && declare -r KEYWORDS="$(echo "$options_string" | cut -d'|' -f 3)"
+    declare -r DATE_TAKEN="$(echo "$options_string" | cut -d'|' -f 4)"
+
+else 
+    
+    declare -r ALBUM=${3+$3}
+    if [[ -z $ALBUM ]]; then
+        echo "[ERROR] No album name given" >&2
+        exit 1
+    fi
+
+    declare -r TITLE=$ALBUM
+    test -v KEYWORDS_OPTION && declare -r KEYWORDS=$KEYWORDS_OPTION
 fi
 
-# TODO make this overwritable via -t option
-declare -r TITLE=$ALBUM
-declare -r DATE=
+exit
 
 
 build_photonumber_filename_with_leading_p() {
@@ -139,10 +174,10 @@ find "$DCIM_DIR" -regextype posix-extended -type f -iregex $EXTENSIONS \
     cp --preserve=timestamps "$photofile" "$target_filename"
     chmod -w "$target_filename"
 
-    echo $target_filename
+    echo "$target_filename"
 
-done | xargs --no-run-if-empty $CREATE_SIDECAR_CMD \
-    ${CREATOR+-c "$CREATOR"} ${KEYWORDS+-k "$KEYWORDS"} "$SIDECAR_TEMPLATES_DIR" | \
+done | xargs --no-run-if-empty "$CREATE_SIDECAR_CMD" \
+    "${CREATOR+-c "$CREATOR"}" "${KEYWORDS+-k "$KEYWORDS"}" "$SIDECAR_TEMPLATES_DIR" | \
 # the output of actual copying of the photos (i.e. the target filenames of the photos) is swallowed by create_sidecar
 # therefore, print all filenames (photos and sidecars) in a final step
 while read -r sidecar_file; do
