check parameters

diff --git a/rename b/rename
--- a/rename
+++ b/rename
@@ -5,11 +5,13 @@ set -e
 export PATH="$(dirname $(readlink -f "$0")):$PATH"
 
 declare -r NEW_NAME=$1
-# FIXME check that NEW_NAME is not empty
+if [[ -z $NEW_NAME ]]; then
+    echo "Parameter with new name is missing" >&2
+    exit 1
+fi
 
 shift 1
 declare -r PHOTOS_TO_RENAME=$@
-# FIXME check if all are photo files, exit if not
 
 set -u
 
