fixed several issues in set_iptc_in_sidecar. simplified params checking

diff --git a/set_iptc_keywords b/set_iptc_keywords
--- a/set_iptc_keywords
+++ b/set_iptc_keywords
@@ -9,10 +9,8 @@ declare -r KEYWORDS=$1
 if [[ -z $KEYWORDS ]]; then
 	echo "No keywords" >&2
 	exit 1
-fi
-
-if [[ -f $KEYWORDS || -d $KEYWORDS ]]; then
-	echo "Keywords parameter seems to be a file - actual keywords parameter is missing?"
+elif [[ -f $KEYWORDS || -d $KEYWORDS ]]; then
+	echo "Keywords parameter seems to be a file or directory - actual keywords parameter is missing?"
 	exit 1
 fi
 
@@ -23,33 +21,37 @@ set -u
 
 set_iptc_in_sidecar() {
 	local -r sidecar_file=$1
-	echo "sidecar $sidecar_file" >&2
-
-	local new_keywords=$KEYWORDS
-	local old_keywords=$(sed -rn '/\[IPTC\]/,/^$/s/Keywords=(.+);+$/\1/p' "$sidecar_file")
+	local new_keywords=
 
 	local -r OLD_IFS=$IFS
-	IFS=;
+	IFS=";"
+
+	local old_keywords=$(sed -rn '/\[IPTC\]/,/^$/s/Keywords=(.+);+$/\1/p' "$sidecar_file")
 	for old_keyword in $old_keywords; do 
-		if ! [[ $new_keywords =~ .*$old_keywords.* ]]; then
-			# TODO quote if needed (any spaces)
+		if ! [[ $KEYWORDS =~ .*$old_keyword.* ]]; then
 			new_keywords="$new_keywords;$old_keyword"
 		fi		
 	done
+
+	for new_keyword in $KEYWORDS; do
+		if [[ $new_keyword =~ .+[[:space:]].+ ]]; then
+			new_keyword="\"$new_keyword\""
+		fi
+		new_keywords="$new_keywords$new_keyword;"
+	done
+
 	IFS=$OLD_IFS
 
-	sed -i '/\[IPTC\]/,/^$/ s|Keywords=.*$|Keywords='"$new_keywords"';|' "$sidecar_file"
+	sed -i '/\[IPTC\]/,/^$/ s/Keywords=.*;$/Keywords='"$new_keywords"'/' "$sidecar_file"
 }
 
 set_iptc_in_jpeg() {
 	local -r jpeg_file=$1
-	echo "output jpg $jpeg_file" >&2
 }
 
 
 "$COLLECTOR_CMD" $FILES | while read -r file; do
 
-	echo "file $file" >&2
 	if [[ $file =~ .*\.pp[23]$ ]]; then
 
 		if ! grep "^[IPTC]$" "$file"; then
