fixed logging

diff --git a/set_iptc_keywords b/set_iptc_keywords
--- a/set_iptc_keywords
+++ b/set_iptc_keywords
@@ -10,7 +10,7 @@ if [[ -z $KEYWORDS ]]; then
 	echo "No keywords" >&2
 	exit 1
 elif [[ -f $KEYWORDS || -d $KEYWORDS ]]; then
-	echo "Keywords parameter seems to be a file or directory - actual keywords parameter is missing?"
+	echo "[ERROR] Keywords parameter seems to be a file or directory - actual keywords parameter is missing?" >&2
 	exit 1
 fi
 
