uses change_album and set_title, move_to_album becomes obsolete

diff --git a/apps/move b/apps/move
--- a/apps/move
+++ b/apps/move
@@ -6,15 +6,15 @@ declare -r -x APP_TITLE="Move photos"
 
 declare -r BASE_DIR="$(dirname "$(readlink -e "$0")")/.."
 
-declare -r SELECTOR="$BASE_DIR/apps/selector"
-declare -r MOVE_PHOTOS="$BASE_DIR/lib/move_photos.sh"
+PATH="$BASE_DIR:$BASE_DIR/lib:$BASE_DIR/apps:$PATH"
+
 source "$BASE_DIR/apps/lib/yad.sh"
 source "$BASE_DIR/apps/lib/form_values.sh"
 source "$BASE_DIR/apps/lib/notification.sh"
 
 declare -r SEARCH_DIR=$(readlink -e "${1+$1}")
 
-photos=$("$SELECTOR" "$SEARCH_DIR") 
+photos=$(selector "$SEARCH_DIR") 
 if [[ -z $photos ]]; then
     notify_warning "$APP_TITLE" "No matching photos found"  
     exit 1
@@ -37,19 +37,27 @@ if [[ -z $TARGET_ALBUM_NAME ]]; then
 fi
 memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "album" "$TARGET_ALBUM_NAME" 25
 
+files=$(collect_associated_files.sh "$photos")
+
 declare -r RENAME_PHOTOS_OPTION=$(echo "$move_to_album_params" | cut -d'|' -f 2)
 if [[ $RENAME_PHOTOS_OPTION = "TRUE" ]]; then
-    declare -r RENAME_MODE="b"
-else 
-    declare -r RENAME_MODE="a"
+    files=$(set_title "$TARGET_ALBUM_NAME" "$files")
+    rename_rc=$?
+    if [[ $rename_rc = 0 ]]; then
+        notify_info "$APP_TITLE" "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$TARGET_ALBUM_NAME\" done"
+    else
+        notify_error "$APP_TITLE" \
+            "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$TARGET_ALBUM_NAME\" failed with return code $rename_rc"
+        exit 1
+    fi
 fi
 
-"$MOVE_PHOTOS" -r "$TARGET_ALBUM_NAME" -m $RENAME_MODE "$photos"
-move_photos_rc=$?
-if [[ $move_photos_rc = 0 ]]; then
+change_album "$TARGET_ALBUM_NAME" "$files"
+change_album_rc=$?
+if [[ $change_album_rc = 0 ]]; then
     notify_info "$APP_TITLE" "Moving $(echo "$photos" | wc -l) photos to \"$TARGET_ALBUM_NAME\" done"
 else
     notify_error -e "$APP_TITLE" \
-        "Renaming $(echo "$photos" | wc -l) photos to \"$TARGET_ALBUM_NAME\" failed with return code $move_photos_rc"
+        "Renaming $(echo "$photos" | wc -l) photos to \"$TARGET_ALBUM_NAME\" failed with return code $change_album_rc"
     exit 1
 fi
