move was missing check if no photos found and was not exiting on dialog cancel. other fixes

diff --git a/apps/move b/apps/move
--- a/apps/move
+++ b/apps/move
@@ -31,6 +31,11 @@ old_values_or_default() {
 
 photos=$("$SELECTOR" -o "$SELECTOR_OLD_VALUES" "$SEARCH_DIR")
 
+if [[ -z $photos ]]; then
+    "$POPUP_CMD" -e "Move - error" "No matching photos found"  
+    exit 1
+fi
+
 dialog_text=$(echo -e "Move listed photos\n\n$photos\n\nto a different album:\n\n")
 
 move_to_album_params=$(yad \
@@ -39,10 +44,13 @@ move_to_album_params=$(yad \
     --form \
     --field="New album (required):CBE" "$(old_values_or_default "album" "")" \
     --field="Rename photos:CHK" "FALSE")
+if [[ $? = 252 ]]; then
+    exit
+fi
 
 declare -r TARGET_ALBUM_NAME=$(echo "$move_to_album_params" | cut -d'|' -f 1 | tr ' ' '-')
 if [[ -z $TARGET_ALBUM_NAME ]]; then    
-    "$POPUP_CMD" -e "Move to album - error" "New album name is required"  
+    "$POPUP_CMD" -e "Move - error" "New album name is required"  
     exit 1
 fi
 declare -r RENAME_PHOTOS_OPTION=$(echo "$move_to_album_params" | cut -d'|' -f 2)
