rename now sets new/removes old title from iptc keywords

diff --git a/apps/rename b/apps/rename
--- a/apps/rename
+++ b/apps/rename
@@ -27,29 +27,55 @@ title_field_values=$(remember_list "title" "gnl")
 rename_params=$(run_yad_selector_result_action_dialog "$APP_TITLE" "$photos" "" \
     --form \
     --field="Change photo title(s) to:CBE" "$title_field_values" \
-    --field="Allow case change only:CHK" "FALSE")
+    --field="Allow case change only:CHK" "FALSE" \
+    --field="Add title as a keyword:CHK" "TRUE" \
+    --field="Remove old title keyword:CHK" "FALSE")
 yad_rc=$?
 if [[ $yad_rc = 252 ]] || [[ $yad_rc = 1 ]]; then
     exit
 fi
 
-declare -r NEW_TITLE=$(trim_whitespace "$(get_option_at_index "$rename_params" 1)")
-if [[ -z $NEW_TITLE ]]; then    
+declare -r new_title=$(trim_whitespace "$(get_option_at_index "$rename_params" 1)")
+if [[ -z $new_title ]]; then    
     notify_warning "$APP_TITLE" "New photo title is required"  
     exit 1
 fi
-memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "title" "$NEW_TITLE" 25
+memorize_form_combobox_values "$MEMORIZED_FORM_VALUES_FILE" "title" "$new_title" 25
+is_option_selected "$rename_params" 2 && declare allow_case_change="-c"
+is_option_selected "$rename_params" 3 && declare add_title_as_keyword=
+is_option_selected "$rename_params" 4 && declare remove_old_title_keyword=
 
-if is_option_selected "$rename_params" 2; then
-    allow_case_change="-c"
+
+if [[ -v remove_old_title_keyword ]]; then
+    # unfortunately, we have to process the photos one by one to remove the
+    # old title because we need the old title from each individual photo...
+    while read -r photo; do
+        remove_keywords "$(title_from_photoid "$photo")" "$photo"
+    done <<<"$photos"
+    rc=$?
+    if [[ $rc != 0 ]]; then
+        notify_error "$APP_TITLE" \
+            "Failed adding title as keyword with return code $rc"
+        exit 1
+    fi
 fi
 
-set_title ${allow_case_change-} "$NEW_TITLE" $photos
-set_title_rc=$?
-if [[ $set_title_rc = 0 ]]; then
-    notify_info "$APP_TITLE" "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$NEW_TITLE\" done"
-else
+if [[ -v add_title_as_keyword ]]; then
+    add_keywords "$new_title" $photos
+    rc=$?
+    if [[ $rc != 0 ]]; then
+        notify_error "$APP_TITLE" \
+            "Failed adding title as keyword with return code $rc"
+        exit 1
+    fi
+fi
+
+set_title ${allow_case_change-} "$new_title" $photos 
+rc=$?
+if [[ $rc != 0 ]]; then
     notify_error "$APP_TITLE" \
-        "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$NEW_TITLE\" failed with return code $set_title_rc"
+        "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$new_title\" failed with return code $set_title_rc"
     exit 1
 fi
+
+notify_info "$APP_TITLE" "Changing title of $(echo "$photos" | wc -l) photo(s) to \"$new_title\" done"
diff --git a/set_title b/set_title
--- a/set_title
+++ b/set_title
@@ -1,6 +1,7 @@
 #! /usr/bin/env bash
 
 set -eu
+set -o pipefail
 shopt -s nocasematch
 
 declare -r BASEDIR="$(dirname "$(readlink -e "$0")")"
@@ -20,11 +21,11 @@ done
 shift $(expr $OPTIND - 1 )
 
 
-declare -r TITLE=$(echo "${1:-}" | tr ' ' '-')
-if [[ -z $TITLE ]]; then
+declare -r new_title=$(echo "${1:-}" | tr ' ' '-')
+if [[ -z $new_title ]]; then
     echo "[ERROR] Title parameter missing" >&2
     exit 1
-elif [[ -f $TITLE || -d $TITLE ]]; then
+elif [[ -f $new_title || -d $new_title ]]; then
 	echo "[ERROR] Title parameter is a file or directory" >&2
 	exit 1
 fi
@@ -45,8 +46,8 @@ apply_set_title() {
 
     local -r photoid=$(basename "$file")
     local -r old_title=${photoid%%_*}
-    if ! [[ -v FORCE_OVERWRITE ]] && [[ $old_title = $TITLE ]]; then
-        echo "[WARN] Cannot change title of $file to \"$TITLE\", same as old title" >&2
+    if ! [[ -v FORCE_OVERWRITE ]] && [[ $old_title = $new_title ]]; then
+        echo "[WARN] Cannot change title of $file to \"$new_title\", same as old title" >&2
         return
     fi    
 
@@ -55,12 +56,12 @@ apply_set_title() {
         local -r restore_write_protection=
     fi
 
-    local -r new_filename="${TITLE}_${filename#*_}"
+    local -r new_filename="${new_title}_${filename#*_}"
     local -r newfile="$(dirname "$file")/$new_filename"
 
     # this is a real error case unlike the other check above (which stems from careless user input)
     if [[ -e $newfile ]] && ! [[ -v FORCE_OVERWRITE ]]; then
-        echo "[ERROR] Cannot change title of $file to \"$TITLE\", file $newfile exists already" >&2
+        echo "[ERROR] Cannot change title of $file to \"$new_title\", file $newfile exists already" >&2
         exit 1
     fi
 
@@ -77,7 +78,6 @@ apply_set_title() {
     echo "$newfile"
 }
 
-set -o pipefail
 if [[ -v READ_PHOTOS_FROM_STDIN ]]; then
     collect_associated_files < /dev/stdin | while read -r file; do apply_set_title "$file"; done
 else 
